services:

  broker:
    build:
      context: .
      dockerfile: Dockerfile
    image: cc7261:pyzmq
    container_name: broker
    volumes:
      - ./broker.py:/app/main.py
    ports:
      - 5555:5555
      - 5556:5556

  servidor:
    build:
      context: .
      dockerfile: Dockerfile_Server
    volumes:
      - ./servidor.py:/app/servidor.py
      - dados_servidor:/data 
    depends_on:
      - broker
      - pubsub-proxy
    deploy:
      replicas: 2
    environment:
    - SERVER_PORT=7000
    ports:
      - "7000-7001:7000"
      - "7100-7101:7100"
      - "7200-7201:7200"

  cliente-1:
    build:
      context: .
      dockerfile: Dockerfile_Client
    volumes:
      - ./Cliente.java:/app/Cliente.java
    depends_on:
      - servidor
    environment:
      - USUARIO=Pedro Henrique
    stdin_open: true
    tty: true

  cliente-2:
    build:
      context: .
      dockerfile: Dockerfile_Client
    volumes:
      - ./Cliente.java:/app/Cliente.java
    depends_on:
      - servidor
    environment:
      - USUARIO=Leonardo
    stdin_open: true
    tty: true

  pubsub-proxy:
    build: 
      context: .
      dockerfile: Dockerfile_Proxy
    container_name: pubsub-proxy
    command: python proxy.py
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 5557:5557
      - 5558:5558
  
  reference:
    build: .
    container_name: reference
    command: python reference.py
    volumes:
      - ./reference.py:/app/reference.py
    ports:
      - "6000:6000"

volumes:
  dados_servidor: 