services:

  broker:
    build:
      context: .
      dockerfile: Dockerfile
    image: cc7261:pyzmq
    container_name: broker
    volumes:
      - ./broker.py:/app/main.py
    ports:
      - 5555:5555
      - 5556:5556

  servidor:
    build:
      context: .
      dockerfile: Dockerfile_Server
    volumes:
      - ./servidor.py:/app/servidor.py
    depends_on:
      - broker
      - pubsub-proxy
    deploy:
      replicas: 2

  cliente:
    build:
      context: .
      dockerfile: Dockerfile_Client
    volumes:
      - ./cliente.java:/app/cliente.java
    depends_on:
      - servidor
    deploy:
      replicas: 2
    stdin_open: true
    tty: true

  pubsub-proxy:
    build: 
      context: .
      dockerfile: Dockerfile_Proxy
    image: python:3.11
    container_name: pubsub-proxy
    command: python proxy.py
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 5557:5557
      - 5558:5558